In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [3]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
vocab_size = 30

encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[26, 6], [18, 27], [29, 19], [26, 23, 23], [16, 16, 27], [6, 6], [12, 16, 28], [29, 25], [29, 1], [14, 6]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length, padding = 'post')
print(padded_reviews)

[[26  6  0  0]
 [18 27  0  0]
 [29 19  0  0]
 [26 23 23  0]
 [16 16 27  0]
 [ 6  6  0  0]
 [12 16 28  0]
 [29 25  0  0]
 [29  1  0  0]
 [14  6  0  0]]


In [6]:
embedded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length = max_length, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

In [8]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(X,y, epochs = 50, verbose = 0)

In [10]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 212ms/step - loss: 0.6353 - accuracy: 0.8000


0.800000011920929

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[11]

array([ 0.0313409 , -0.04098177, -0.04990881,  0.039246  , -0.04593084],
      dtype=float32)